# Generated by Django 5.0.4 on 2025-03-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0033_projecttemplate_meeting_projectmilestone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestone',
            name='dependencies',
        ),
        migrations.RemoveField(
            model_name='projectmilestone',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectTemplate',
        ),
        migrations.DeleteModel(
            name='ProjectMilestone',
        ),
    ]
